version: "3.3"

services:
  db:
    image: postgres:11.5-alpine
    container_name: pg-dev
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: senha
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - redePostgres

  dev-api:
    image: joaomede/nodejs12prod:1.0
    container_name: "dev-api"
    depends_on:
      - db
    links:
      - db
    environment:
      NODE_ENV: "dev"
      HOSTDB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: senha
    env_file:
      - .env
    ports:
      - 5100:80
    command: ./scripts/dev.sh
    expose:
      - 5100
    volumes:
      - .:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/letsencrypt:/etc/letsencrypt
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - redePostgres

  dev-view:
    image: joaomede/nodejs12prod:1.0
    container_name: "dev-view"
    ports:
      - 8080:8080
    links:
      - dev-api
    environment:
      VUE_APP_APIURL: http://localhost:5100
    command: yarn dev
    expose:
      - 8080
    volumes:
      - ./view:/usr/src/app
      - /etc/letsencrypt:/etc/letsencrypt
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - redePostgres

networks:
  redePostgres:
    driver: bridge
